// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuCita.Data;

#nullable disable

namespace TuCita.Migrations
{
    [DbContext(typeof(TuCitaDbContext))]
    partial class TuCitaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TuCita.Models.AgendaTurno", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("datetime2")
                        .HasColumnName("fin");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("inicio");

                    b.Property<decimal>("MedicoId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("medico_id");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.ToTable("agenda_turnos");
                });

            modelBuilder.Entity("TuCita.Models.Cita", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en");

                    b.Property<decimal>("CreadoPor")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("creado_por");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("datetime2")
                        .HasColumnName("fin");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("inicio");

                    b.Property<decimal>("MedicoId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("medico_id");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("motivo");

                    b.Property<decimal>("PacienteId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("paciente_id");

                    b.Property<decimal>("TurnoId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("turno_id");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("TurnoId");

                    b.ToTable("citas");
                });

            modelBuilder.Entity("TuCita.Models.Diagnostico", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("CitaId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("cita_id");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.ToTable("diagnosticos");
                });

            modelBuilder.Entity("TuCita.Models.Especialidad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("especialidades");
                });

            modelBuilder.Entity("TuCita.Models.MedicoEspecialidad", b =>
                {
                    b.Property<decimal>("MedicoId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("medico_id");

                    b.Property<long>("EspecialidadId")
                        .HasColumnType("bigint")
                        .HasColumnName("especialidad_id");

                    b.HasKey("MedicoId", "EspecialidadId");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("medico_especialidad");
                });

            modelBuilder.Entity("TuCita.Models.NotaClinica", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("CitaId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("cita_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en");

                    b.Property<decimal>("MedicoId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("medico_id");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nota");

                    b.Property<decimal>("PacienteId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("paciente_id");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("notas_clinicas");
                });

            modelBuilder.Entity("TuCita.Models.Notificacion", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("canal");

                    b.Property<decimal?>("CitaId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("cita_id");

                    b.Property<string>("Contenido")
                        .HasColumnType("JSON")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en");

                    b.Property<bool>("Enviada")
                        .HasColumnType("bit")
                        .HasColumnName("enviada");

                    b.Property<DateTime?>("EnviadaEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("enviada_en");

                    b.Property<string>("Error")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("error");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("UsuarioId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("notificaciones");
                });

            modelBuilder.Entity("TuCita.Models.PerfilMedico", b =>
                {
                    b.Property<decimal>("UsuarioId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("usuario_id");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Biografia")
                        .HasColumnType("TEXT")
                        .HasColumnName("biografia");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ciudad");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("direccion");

                    b.Property<double?>("Latitud")
                        .HasColumnType("float")
                        .HasColumnName("latitud");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float")
                        .HasColumnName("longitud");

                    b.Property<string>("NumeroLicencia")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("numero_licencia");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("pais");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("provincia");

                    b.HasKey("UsuarioId");

                    b.ToTable("perfil_medico");
                });

            modelBuilder.Entity("TuCita.Models.PerfilPaciente", b =>
                {
                    b.Property<decimal>("UsuarioId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("usuario_id");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Identificacion")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("identificacion");

                    b.Property<string>("TelefonoEmergencia")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("telefono_emergencia");

                    b.HasKey("UsuarioId");

                    b.ToTable("perfil_paciente");
                });

            modelBuilder.Entity("TuCita.Models.Receta", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("CitaId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("cita_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en");

                    b.Property<string>("Indicaciones")
                        .HasColumnType("TEXT")
                        .HasColumnName("indicaciones");

                    b.HasKey("Id");

                    b.HasIndex("CitaId");

                    b.ToTable("recetas");
                });

            modelBuilder.Entity("TuCita.Models.RecetaItem", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Dosis")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("dosis");

                    b.Property<string>("Duracion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("duracion");

                    b.Property<string>("Frecuencia")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("frecuencia");

                    b.Property<string>("Medicamento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("medicamento");

                    b.Property<string>("Notas")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("notas");

                    b.Property<decimal>("RecetaId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("receta_id");

                    b.HasKey("Id");

                    b.HasIndex("RecetaId");

                    b.ToTable("receta_items");
                });

            modelBuilder.Entity("TuCita.Models.Rol", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("TuCita.Models.RolUsuario", b =>
                {
                    b.Property<decimal>("UsuarioId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("RolId")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("rol_id");

                    b.Property<DateTime>("AsignadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("asignado_en");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("roles_usuarios");
                });

            modelBuilder.Entity("TuCita.Models.Usuario", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("apellido");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("EmailNormalizado")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email_normalizado")
                        .HasComputedColumnSql("LOWER([email])", true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("TokenRecuperacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("token_recuperacion");

                    b.Property<DateTime?>("TokenRecuperacionExpira")
                        .HasColumnType("datetime2")
                        .HasColumnName("token_recuperacion_expira");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalizado")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("TuCita.Models.AgendaTurno", b =>
                {
                    b.HasOne("TuCita.Models.PerfilMedico", "Medico")
                        .WithMany("AgendaTurnos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("TuCita.Models.Cita", b =>
                {
                    b.HasOne("TuCita.Models.Usuario", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuCita.Models.PerfilMedico", "Medico")
                        .WithMany("Citas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuCita.Models.PerfilPaciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuCita.Models.AgendaTurno", "Turno")
                        .WithMany("Citas")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creador");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("TuCita.Models.Diagnostico", b =>
                {
                    b.HasOne("TuCita.Models.Cita", "Cita")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("TuCita.Models.MedicoEspecialidad", b =>
                {
                    b.HasOne("TuCita.Models.Especialidad", "Especialidad")
                        .WithMany("MedicosEspecialidades")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuCita.Models.PerfilMedico", "Medico")
                        .WithMany("EspecialidadesMedico")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("TuCita.Models.NotaClinica", b =>
                {
                    b.HasOne("TuCita.Models.Cita", "Cita")
                        .WithMany("NotasClinicas")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuCita.Models.PerfilMedico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuCita.Models.PerfilPaciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("TuCita.Models.Notificacion", b =>
                {
                    b.HasOne("TuCita.Models.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuCita.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TuCita.Models.PerfilMedico", b =>
                {
                    b.HasOne("TuCita.Models.Usuario", "Usuario")
                        .WithOne("PerfilMedico")
                        .HasForeignKey("TuCita.Models.PerfilMedico", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TuCita.Models.PerfilPaciente", b =>
                {
                    b.HasOne("TuCita.Models.Usuario", "Usuario")
                        .WithOne("PerfilPaciente")
                        .HasForeignKey("TuCita.Models.PerfilPaciente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TuCita.Models.Receta", b =>
                {
                    b.HasOne("TuCita.Models.Cita", "Cita")
                        .WithMany("Recetas")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("TuCita.Models.RecetaItem", b =>
                {
                    b.HasOne("TuCita.Models.Receta", "Receta")
                        .WithMany("Items")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("TuCita.Models.RolUsuario", b =>
                {
                    b.HasOne("TuCita.Models.Rol", "Rol")
                        .WithMany("RolesUsuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuCita.Models.Usuario", "Usuario")
                        .WithMany("RolesUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TuCita.Models.AgendaTurno", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("TuCita.Models.Cita", b =>
                {
                    b.Navigation("Diagnosticos");

                    b.Navigation("NotasClinicas");

                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("TuCita.Models.Especialidad", b =>
                {
                    b.Navigation("MedicosEspecialidades");
                });

            modelBuilder.Entity("TuCita.Models.PerfilMedico", b =>
                {
                    b.Navigation("AgendaTurnos");

                    b.Navigation("Citas");

                    b.Navigation("EspecialidadesMedico");
                });

            modelBuilder.Entity("TuCita.Models.PerfilPaciente", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("TuCita.Models.Receta", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TuCita.Models.Rol", b =>
                {
                    b.Navigation("RolesUsuarios");
                });

            modelBuilder.Entity("TuCita.Models.Usuario", b =>
                {
                    b.Navigation("PerfilMedico");

                    b.Navigation("PerfilPaciente");

                    b.Navigation("RolesUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
